### ISSUE TITLE
Could not find file ./pass.js

### ISSUE THREAD

**Issue by Boeny** [ushliypakostnik/robot-game-backend#1]
You don't have a `pass.js` file in the project, so, `npm start` doesn't work

**Comment by ushliypakostnik** [comment]
Hey! This "secret" is the MongoDB cloud access key.

Create a database at https://cloud.mongodb.com/

Create @/src/pass.js:

`const PASS = {
  DB: {
    url: 'mongodb+srv://admin:[...your key...]',
  },
  RANDOM_BYTES: 48,
};

export default PASS;`

And write your correct key into it

**Comment by ushliypakostnik** [comment]
Added example https://github.com/ushliypakostnik/robot-game-backend/blob/master/src/pass.js.tmpl and updated README.md

Thanks!

**Comment by Boeny** [comment]
Thank you!
